### ISSUE TITLE
Check if both methods are needed

### ISSUE THREAD

**Issue by olekscode** [PolyMathOrg/DataFrame#109]
There was a merge conflict between the two methods, so I accepted both of them. @AtharvaKhare could you please check if both of these methods are needed (together with the corresponding tests) and remove one of them if it is deprecated.

```Smalltalk
DataFrameInternal >> removeRowsOfColumnElementsSatisfing: aBlock onColumn: columnNumber
DataFrameInternal >> replaceMissingValuesStrings: aSet
```

**Comment by AtharvaKhare** [comment]
Both these methods are needed, I am not sure why there was a merge conflict, since they are independent.

The method
```
DataFrameInternal >> removeRowsOfColumnElementsSatisfing: aBlock onColumn: columnNumber
```
is for general removal of rows following a condition, eg: dropping rows having nil at any feature.

The second method is for replacing (and not removing) missing values defined by `aSet`.

I think both these methods are needed.

**Comment by olekscode** [comment]
OK!
