### ISSUE TITLE
DataFrame class>>withRows:columnNames: fails when the given rows are empty.

### ISSUE THREAD

**Issue by tomooda** [PolyMathOrg/DataFrame#122]
creating a DataFrame with empty row results in empty columns, and therefore columnNames: fails due to mismatching number of columns.

**Comment by olekscode** [comment]
Hello @tomooda 
I'm not sure that I understood correctly.

### Example 1

```Smalltalk
df := DataFrame
    withRows: #((Honore 24)(Steven 32))
    columnNames: #(Name Age).
```
This will give you a data frame with 2 rows and 2 columns:
```
+--------------+
| Name   | Age |
+--------------+
| Honore |  24 |
| Steven |  32 |
+--------------+
```

### Example 2

```Smalltalk
df := DataFrame
    withColumnNames: #(Name Age).
```
This will give you an empty data frame with no rows but 2 named columns:
```
+--------------+
| Name   | Age |
+--------------+
```

### Example 3

```Smalltalk
df := DataFrame
    withRows: #()
    columnNames: #(Name Age).
```
This throws an exception because it expects to get at least one row with two values for each of the columns.

---------------------------

Perhaps, it would make sense to check if the array of rows is empty and call `DataFrame class >> withColumnNames:` if it is.

Is that what you meant?

**Comment by tomooda** [comment]
Yes, please refer to https://github.com/PolyMathOrg/DataFrame/pull/123 .
I sometimes generate a dataframe from external data source and don't want to check emptiness in the client code.
I think Example 3 should create an empty dataframe with two column names to make a consistent semantics.

**Comment by olekscode** [comment]
Thank you!
