### ISSUE TITLE
Why dataFrame core depends on DataSource

### ISSUE THREAD

**Issue by Ducasse** [PolyMathOrg/DataFrame#161]
This a strange idea to have the core depending on morphic!

**Comment by olekscode** [comment]
That's because in the older version of Pharo inspector we had to override `showWithGlamourIn:` to define the inspector view.
And to make a table that can be displayed with Glamour, I had to use FastTable and some Morphic magic...
I think that's the reason

Now that method should be removed and replaced with a nice Spec view.
So it's related to this: https://github.com/PolyMathOrg/DataFrame/issues/147
