### ISSUE TITLE
Error loading master

### ISSUE THREAD

**Issue by tinchodias** [PolyMathOrg/DataFrame#162]
In a Pharo10 I run:
```
Metacello new
  baseline: 'DataFrame';
  repository: 'github://PolyMathOrg/DataFrame/src';
  load.
```

I get:

Could not resolve: BaselineOfRandomPartitioner [BaselineOfRandomPartitioner] in <path>/pharo-local/package-cache git@github.com:pharo-ai/RandomPartitioner.git[master]

**Comment by hernanmd** [comment]
I don't understand why DataFrame depends on RandomPartitioner?

**Comment by Ducasse** [comment]
Me neither!

**Comment by tinchodias** [comment]
It sounds that in any case, that project should extend this one.

Anyway, the error apparently comes from a mismatch with the baseline name here:

https://github.com/PolyMathOrg/DataFrame/blob/dadc51742e887b3a571c3db9b3c376c676587639/src/BaselineOfDataFrame/BaselineOfDataFrame.class.st#L23

And that the ai's project baseline was renamed:
https://github.com/pharo-ai/random-partitioner/blob/master/src/BaselineOfAIRandomPartitioner/BaselineOfAIRandomPartitioner.class.st

@jordanmontt ?

**Comment by jordanmontt** [comment]
Yes, I also thing that DataFrame should not depend on Random Partitioner.

Nevertheles, I was my fault, sorry. I renamed the baseline to `AIRandomPartitioner` because we agreed to have the `AI` prefix on all pharo-ai projects/classes. That is causing the error.

If is necessary that DataFrame depends on RandomPartitoner, we can make to depend to a fixed version. I just made a release

**Comment by jordanmontt** [comment]
Ok, I removed the dependecy of random partitioner. Now the script from the readme is working

**Comment by tinchodias** [comment]
Thanks!
