### ISSUE TITLE
Add removeDuplicates method

### ISSUE THREAD

**Issue by Joshua-Dias-Barreto** [PolyMathOrg/DataFrame#219]
This method would be similar to the [drop_duplicates()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html) method in pandas and [unique()](https://dataframes.juliadata.org/stable/lib/functions/#Base.unique) method in Julia.

**Comment by olekscode** [comment]
I think this method should be consistent with the similar method for `DataSeries`. For now, the `DataSeries` method is called `uniqueValues`.

But I think it should be better if we rename it to `removeDuplicates` - this method would remove duplicate values from the series. Then the `DataFrame` method would also be called `removeDuplicates` and it would remove duplicate rows.

I like `remove...` more than `drop...` because it would be easier for users to find this method.
Essentially dropping is removing
So I think we should be consistent and use the same vocabulary here
