### ISSUE TITLE
Add more find-select methods

### ISSUE THREAD

**Issue by Joshua-Dias-Barreto** [PolyMathOrg/DataFrame#220]
Implement a method **isin** which is equivalent to the pandas method [isin()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html).

Also implement methods like **findAll: atRow:**  and  **findAllIndicesOf :atRow:**

**Comment by olekscode** [comment]
Could you please explain what would this method do? And maybe propose a more descriptive name for it
Because we should also be consistent with the standard API of Pharo collections

There is method `includes:` which checks if the given value is in the collection
And a method `allSatisfy:` which applies a boolean block to each value and checks if all of them answer true

For example:
```st
series allSatisfy: [ :each | #(1 2) includes: each ]
```

If this operation is commonly used, we can add a method for it, but we should also be careful not to make the API too large and too complex

**Comment by Joshua-Dias-Barreto** [comment]
Maybe `contains` is a more descriptive name.

This method should return a boolean dataframe, indicating true wherever the given values are present in the dataframe.

    testContains
    | df expected |
    df := DataFrame
    withRows: #(
    ('A1' 'B1' 'C1' 'D1')
    ('A2' 'B2' 'C2' 'D2'))
    columnNames: #('A' 'B' 'C' 'D').

    expected := DataFrame
    withRows: #(
    (true true false false)
    (true true false false))
    columnNames: #('A' 'B' 'C' 'D').

    self assert : df contains: #('A1' 'A2' 'B1' 'B2') equals: expected.

This method is mainly used for filtering, the applications of pandas.isin() can be seen [here](https://sparkbyexamples.com/pandas/pandas-isin-explained-with-examples/#:~:text=pandas%20Series.,DataFrame%20to%20filter%20the%20rows.).
