### ISSUE TITLE
Sort dataseries not keeping original index of the data, so cannot retrieve the row from the df

### ISSUE THREAD

**Issue by philippeback** [PolyMathOrg/DataFrame#6]
e.g. 

```smalltalk
distances := (1 to: rows) collect: [ :row |  row -> (alpha - (lut at: row at: 4)) abs].

df addColumn: distances named: #Distance.

distancesDataSerie := df column: #Distance.

distancesDataSerie sorted: [ :a :b | a value < b value ].
```

But then there is no way to find back where each ds entry came from in the df.

It would be even better to be able to sort the df by a given column, or a set of such columns, or an arbitrary composite criteria (read: a block)

**Comment by philippeback** [comment]
This is why I used associations. But then the DataSerie and DataFrame are not that powerful, which was why I was using them.

**Comment by philippeback** [comment]
Because what I need is to get a ranked dataset based on that distance.

**Comment by philippeback** [comment]
Basically DataFrame should have TSortable as well, using rows.

**Comment by olekscode** [comment]
I don't know if it's a good idea for DataFrame to implement TSortable. I mean, yes, now it has this trait as a subclass of SequenceableCollection, but maybe it should be blocked somehow. Either by `shouldNotImplement` or by subclassing DataFrame from something different than SequenceableCollection - for example, from Collection.

TSortable has one-dimensional logic. We could implement message `sort:` since it accepts a block and use it like this

```smalltalk
df sort [ :row1 :row2 |
    (row1 atKey: #Population) <= (row2 atKey: Population) ].
```

But this is not very readable. So instead of implementing messages of TSortable, I've implemented `orderBy:` and `orderBy:using:`, similar to what we have in SQL

```smalltalk
df orderBy: #Population.
```

`orderByUsing:` allows us to specify the way of sorting elements in more smalltalk-ish way than using keywords like ASCENDING or DESCENDING. Here is an example of sorting a data frame by the Population in descending order

```smalltalk
df orderBy: #Population using: [ :a :b | a >= b ].
```

Let me know what you think about this
